[package]
name = "crop_image"
version = "0.1.0"
authors = ["Daan Michiels <michielsdaan@gmail.com>"]
edition = "2021"


[dependencies]
clap = { version = "4.0.25", features = ["derive"] }
image = "0.24.5"
